import React, { useState } from 'react';
import axios from 'axios';
import { useAuth } from '../contexts/authContext'; // Ensure correct path
import PropTypes from 'prop-types';

const CreateTicket = ({ organizationId, users = [] }) => {
  const { currentUser, loading } = useAuth();

  const [ticketData, setTicketData] = useState({
    // Removed ticket_number as it's generated by the backend
    status: 'Open',
    reported_date: '',
    related_record: '',
    first_name: '',
    last_name: '',
    email: '',
    contact: '',
    location: '',
    // Removed opened_by as it's set by the backend
    category: '',
    impact: '',
    urgency: '',
    // Removed priority; assuming backend calculates it based on impact and urgency
    assignment_group: '',
    assignee: '',
    subject: '',
    description: '',
    attachment: null,
  });

  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const categoryOptions = [
    { value: 'Incident', label: 'Incident' },
    { value: 'Request', label: 'Request' },
    { value: 'Problem', label: 'Problem' },
  ];

  const impactOptions = [
    { value: 'Low', label: 'Low' },
    { value: 'Middle', label: 'Middle' },
    { value: 'High', label: 'High' },
    { value: 'Critical', label: 'Critical' },
  ];

  const urgencyOptions = [
    { value: 'Low', label: 'Low' },
    { value: 'Middle', label: 'Middle' },
    { value: 'High', label: 'High' },
    { value: 'Critical', label: 'Critical' },
  ];

  // Handle form field changes
  const handleChange = (e) => {
    const { name, value } = e.target;
    setTicketData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  // Handle file input changes
  const handleFileChange = (e) => {
    setTicketData((prevData) => ({
      ...prevData,
      attachment: e.target.files[0],
    }));
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    setIsSubmitting(true);

    const formData = new FormData();
    Object.keys(ticketData).forEach((key) => {
      // Only append fields that are not empty
      if (ticketData[key] !== '') {
        formData.append(`ticket[${key}]`, ticketData[key]);
      }
    });

    try {
      const response = await axios.post(
        `/api/v1/organizations/${organizationId}/tickets`,
        formData,
        {
          headers: {
            'Content-Type': 'multipart/form-data',
            Authorization: `Bearer ${localStorage.getItem('token')}`,
          },
        }
      );

      const { ticket_number } = response.data;
      setSuccess(`Ticket created successfully! Ticket Number: ${ticket_number}`);

      // Optionally, reset the form
      setTicketData({
        status: 'Open',
        reported_date: '',
        related_record: '',
        first_name: '',
        last_name: '',
        email: '',
        contact: '',
        location: '',
        category: '',
        impact: '',
        urgency: '',
        assignment_group: '',
        assignee: '',
        subject: '',
        description: '',
        attachment: null,
      });
    } catch (error) {
      if (error.response && error.response.data && error.response.data.errors) {
        setError(error.response.data.errors.join(', '));
      } else {
        setError('Failed to create ticket. Please try again.');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  // Show loading state while fetching user data
  if (loading) {
    return <div>Loading...</div>; // Replace with a spinner if desired
  }

  // Show error if user is not authenticated
  if (!currentUser) {
    return <div>Please log in to create a ticket.</div>; // Or redirect to login page
  }

  return (
    <div className="bg-blue-700 container mx-auto p-2">
      <div className="p-6 bg-gray-300 shadow rounded-lg mt-12">
        <div className="p-2 mx-auto rounded-b-lg bg-blue-700 shadow-2xl mb-6">
          <h2 className="text-xl mb-6 text-white">Log an Incident</h2>
        </div>
        {error && <p className="text-red-500">{error}</p>}
        {success && <p className="text-green-500">{success}</p>}

        <form onSubmit={handleSubmit}>
          {/* Ticket details grid */}
          <div className="grid grid-cols-3 gap-4">
            <div className="col-span-1">
              <label className="block text-sm font-medium">Ticket Number</label>
              <input
                type="text"
                name="ticket_number"
                value={ticketData.ticket_number}
                readOnly
                className="w-full py-2 px-3 border border-gray-300 text-gray-900 text-sm rounded-b-lg"
              />
              {/* Since ticket_number is generated by the backend, it's initially empty */}
            </div>

            <div className="col-span-1 flex items-center justify-center">
              <button
                type="button"
                className="py-2 px-4 text-white font-bold rounded-md bg-gradient-to-r from-blue-400 to-blue-600 hover:from-blue-500 hover:to-blue-700"
                onClick={() => {
                  // Implement functionality to relate to an existing record
                  // For example, open a modal or navigate to a different page
                  alert('Feature to relate to an existing record is not implemented yet.');
                }}
              >
                Relate to an Existing Record
              </button>
            </div>

            <div className="col-span-1">
              <label className="block text-sm font-medium">Reported Date</label>
              <input
                type="datetime-local"
                name="reported_date"
                value={ticketData.reported_date}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
                required
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4 mt-4">
            <div>
              <label className="block text-sm font-medium">Ticket Status</label>
              <select
                name="status"
                value={ticketData.status}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
              >
                <option value="Open">Open</option>
                <option value="Pending">Pending</option>
                <option value="Closed">Closed</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium">Related Record</label>
              <select
                name="related_record"
                value={ticketData.related_record}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
              >
                <option value="">Select Related Record</option>
                {/* Populate related records as needed */}
              </select>
            </div>
          </div>

          <div className="mt-10"></div>

          <h3 className="text-xl font-semibold mb-4 mt-8 text-blue-600">Caller Details</h3>
          <div className="grid grid-cols-2 gap-8">
            <div>
              <label className="block text-sm font-medium">First Name <span className="text-red-500">*</span></label>
              <input
                type="text"
                name="first_name"
                value={ticketData.first_name}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
                required
              />

              <label className="block text-sm font-medium mt-4">Last Name <span className="text-red-500">*</span></label>
              <input
                type="text"
                name="last_name"
                value={ticketData.last_name}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
                required
              />

              <label className="block text-sm font-medium mt-4">Email <span className="text-red-500">*</span></label>
              <input
                type="email"
                name="email"
                value={ticketData.email}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
                required
              />

              <label className="block text-sm font-medium mt-4">Contact No.</label>
              <input
                type="text"
                name="contact"
                value={ticketData.contact}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
              />

              <label className="block text-sm font-medium mt-4">Location</label>
              <input
                type="text"
                name="location"
                value={ticketData.location}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
              />
            </div>

            <div>
              {/* Opened By Field */}
              <div className="mt-4">
                <label className="block text-sm font-medium">Opened By</label>
                <input
                  type="text"
                  name="opened_by_display"
                  value={`${currentUser.first_name} ${currentUser.last_name}`}
                  readOnly
                  className="w-full py-2 px-3 border border-gray-300 rounded bg-gray-100"
                />
                {/* Since opened_by is set by the backend, no need to include it in the form data */}
              </div>

              <label className="block text-sm font-medium mt-4">Category <span className="text-red-500">*</span></label>
              <select
                name="category"
                value={ticketData.category}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
                required
              >
                <option value="">Select Category</option>
                {categoryOptions.map(option => (
                  <option key={option.value} value={option.value}>{option.label}</option>
                ))}
              </select>

              <label className="block text-sm font-medium mt-4">Impact <span className="text-red-500">*</span></label>
              <select
                name="impact"
                value={ticketData.impact}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
                required
              >
                <option value="">Select Impact</option>
                {impactOptions.map(option => (
                  <option key={option.value} value={option.value}>{option.label}</option>
                ))}
              </select>

              <label className="block text-sm font-medium mt-4">Urgency <span className="text-red-500">*</span></label>
              <select
                name="urgency"
                value={ticketData.urgency}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
                required
              >
                <option value="">Select Urgency</option>
                {urgencyOptions.map(option => (
                  <option key={option.value} value={option.value}>{option.label}</option>
                ))}
              </select>

              {/* Additional fields */}
              <label className="block text-sm font-medium mt-4">Assignment Group <span className="text-red-500">*</span></label>
              <input
                type="text"
                name="assignment_group"
                value={ticketData.assignment_group}
                onChange={handleChange}
                className="w-full py-2 px-3 border border-gray-300 rounded"
                required
              />
            </div>
          </div>

          {/* Assignee */}
          <div className="mt-6">
            <label className="block text-sm font-medium">Assignee <span className="text-red-500">*</span></label>
            <select
              name="assignee"
              value={ticketData.assignee}
              onChange={handleChange}
              className="w-full py-2 px-3 border border-gray-300 rounded"
              required
            >
              <option value="">Select Assignee</option>
              {users.map(user => (
                <option key={user.id} value={user.id}>
                  {user.first_name} {user.last_name}
                </option>
              ))}
            </select>
          </div>

          <div className="mt-6">
            <label className="block text-sm font-medium">Subject <span className="text-red-500">*</span></label>
            <input
              type="text"
              name="subject"
              value={ticketData.subject}
              onChange={handleChange}
              className="w-full py-2 px-3 border border-gray-300 rounded"
              required
            />
          </div>

          <div className="mt-6">
            <label className="block text-sm font-medium">Description <span className="text-red-500">*</span></label>
            <textarea
              name="description"
              value={ticketData.description}
              onChange={handleChange}
              className="w-full py-2 px-3 border border-gray-300 rounded"
              required
            />
          </div>

          <div className="mt-6">
            <label className="block text-sm font-medium">Attachment</label>
            <input
              type="file"
              name="attachment"
              onChange={handleFileChange}
              className="w-full py-2 px-3 border border-gray-300 rounded"
              accept=".jpg,.jpeg,.png,.pdf" // Restrict file types as needed
            />
          </div>

          <div className="mt-6 text-right">
            <button
              type="submit"
              disabled={isSubmitting}
              className={`py-2 px-4 text-white font-bold rounded-md bg-gradient-to-r from-blue-400 to-blue-600 hover:from-blue-500 hover:to-blue-700 ${
                isSubmitting ? 'opacity-50 cursor-not-allowed' : ''
              }`}
            >
              {isSubmitting ? 'Submitting...' : 'Submit'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

CreateTicket.propTypes = {
  organizationId: PropTypes.number.isRequired,
  users: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.number.isRequired,
      first_name: PropTypes.string.isRequired,
      last_name: PropTypes.string.isRequired,
    })
  ).isRequired,
};

export default CreateTicket;
